import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Checkbox from "../components/Checkbox";
import CreatePersonForm from "../components/CreatePersonForm";
import StationView from "../components/StationView";
import { Person } from "../models/Person";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [started, setStarted] = useState<boolean>(false);
  const [autoSkipOnTimerEnd, setAutoSkipOnTimerEnd] = useState<boolean>(false);

  const [persons, setPersons] = useState<Person[]>([]);

  function resetTest() {
    setStarted(false);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Finnentest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-512x512.png" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Finnentest</h1>

        {started ? (
          <>
            <div className={styles.stationViewsContainer}>
              {persons.map((p) => (
                <StationView
                  key={p.name}
                  person={p}
                  autoSkipOnTimerEnd={autoSkipOnTimerEnd}
                />
              ))}
            </div>
            <button onClick={resetTest} className={styles.resetTestButton}>
              Reset Test
            </button>
          </>
        ) : (
          <>
            <CreatePersonForm
              addPerson={(person: Person) => {
                if (!persons.map((p) => p.name).includes(person.name))
                  setPersons((state) => [...state, person]);
              }}
            />
            {persons.map((p) => (
              <div key={p.name}>
                {p.name}, startDruck: {p.druck.start}
                <br />
              </div>
            ))}
            <Checkbox
              checked={autoSkipOnTimerEnd}
              setChecked={setAutoSkipOnTimerEnd}
              label="autoSkipOnTimerEnd"
            />
            <button
              onClick={() => setStarted(true)}
              disabled={persons.length === 0}
              className={styles.startTestButton}
            >
              Start Test
            </button>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
